services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
        - mariadb:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
        - wordpress:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
       - wordpress:/var/www/html

volumes:
    mariadb:
        driver: local
        name: mariadb
        driver_opts:
            type: none
            o: "bind"
            device: ~/data/mariadb
    wordpress:
        driver: local
        name: wordpress
        driver_opts:
            type: none
            o: "bind"
            device: ~/data/wordpress


networks:
  inception:
